import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} bg-white h-screen antialiased`}
      >
        <Header />

        <main className="h-full mt-32">{children}</main>
        <div className="p-10 max-h-60 h-full w-full">
          <Footer />
        </div>
         <noscript>
          <style>{`
            header {
              top: 0 !important;
              backdrop-filter: blur(10px);
              background-color: rgba(255, 255, 255, 0.5);
            }
          `}</style>
        </noscript>
      </body>
    </html>
  );
}
